[build-system]
requires = [
    "setuptools>=80.3.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "splent_marketplace_app"
version = "0.0.1"
description = "splent_marketplace_app is an app built with SPLENT (https://www.splent.io)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "watchdog",
    "locust",
]
core = [
    "splent_framework",
]

[tool.splent]
cli_version = "1.14.0"
features = [
    "splent_io/splent_feature_apikeys@v0.1.0",
    "splent_io/splent_feature_spl_registry@v0.1.0",
    "splent_io/splent_feature_theme@v0.2.1",
    "splent_io/splent_feature_settings@v0.2.1",
    "splent_io/splent_feature_auth@v1.6.2",
    "splent_io/splent_feature_session_filesystem@v1.1.1",
    "splent_io/splent_feature_marketplace@v0.1.1",
    "splent_io/splent_feature_configurator@v0.1.0",
    "splent_io/splent_feature_skin_store@v0.1.1",
    "splent_io/splent_feature_signup@v0.1.0",
]
features_dev = [
    "splent_io/splent_feature_admin@v1.1.1",
]
features_prod = []
spl = "marketplace_spl"

[tool.splent.layout]
base_template = "base_template.html"
hooks = [
    "layout.head.css",
    "layout.sidebar.top",
    "layout.anonymous_sidebar",
    "layout.authenticated_sidebar",
    "layout.sidebar.authenticated.items",
    "layout.navbar.anonymous",
    "layout.navbar.authenticated",
    "layout.footer",
    "layout.scripts",
]

[tool.splent.spl_model]
mirror = "uvlhub.io"
doi = "10.5281/zenodo.21610309"
concept_doi = ""
version = ""
file = "marketplace_spl.uvl"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
